@host=http://localhost:5087

POST {{host}}/auth/register
Content-Type: application/json

{
  "firstName": "Rain",
  "lastName": "Hu",
  "email": "rain.hu@advantech.com",
  "password": "1q2w3E*"
}

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhMGZmMGMzMy0zMzkyLTRkMDItYjE2Ny0zMGI4ZWQyNjJhMzIiLCJnaXZlbl9uYW1lIjoiUmFpbiIsImZhbWlseV9uYW1lIjoiSHUiLCJqdGkiOiIzNmEwOWI0Ni1iMjg1LTRkNDAtYTAyMy1hYjdlOTA3MmZmYjAiLCJleHAiOjE3NTQ5MTA2MTMsImlzcyI6IkNsZWFuQXJjaCIsImF1ZCI6IkNsZWFuQXJjaCJ9.5RZ3PolyfwgS_vVk5P8_lcDFZL2qo15jCVdnv0f-qgc